### ISSUE TITLE
使用 gulp-less 编译 @import (reference) '~antd/es/style/themes/index.less';

### ISSUE THREAD

**Issue by yemuguliunian** [yemuguliunian/issues#1]
原文件
```less
@import (reference) '~antd/es/style/themes/index.less';

.text {
    color: fade(@black, 45%);
}
```

使用`gulp-less`编译

```js
const less = require('gulp-less');
const LessPluginAutoPrefix = require('less-plugin-autoprefix');
const NpmImportPlugin = require('less-plugin-npm-import');
const libDir = path.join(process.cwd(), 'lib');

gulp.task('less', function() {
    const lessStream = gulp.src('./components/**/*.less');
    const lessToCss = lessStream
        .pipe(
            less({
                javascriptEnabled: true,
                plugins: [
                    new NpmImportPlugin({ prefix: '~' }),
                    new LessPluginAutoPrefix({ browsers: ['last 2 versions', 'IE 9'] }),
                ],
            }),
        )
        .pipe(gulp.dest(libDir));

    return merge2([lessToCss]);
});
```
