### ISSUE TITLE
gulp编译css支持css modules

### ISSUE THREAD

**Issue by yemuguliunian** [yemuguliunian/issues#13]
```js
const Core = require('css-modules-loader-core');
const genericNames = require('generic-names');
const less = require('gulp-less');
const postcss = require('gulp-postcss');

const core = new Core([
    Core.values,
    Core.localByDefault,
    Core.extractImports,
    Core.scope({
        generateScopedName: genericNames('[local]___[hash:base64:5]'),
    }),
]);

gulp.task('less', function() {
    const lessStream = gulp.src('./components/**/*.less');
    const lessToCss = lessStream
        .pipe(
            less({
                plugins: [new LessPluginAutoPrefix({ browsers: ['last 2 versions', 'IE 9'] })],
            }),
        )
        .pipe(postcss(core.plugins))
        .pipe(gulp.dest(libDir));

    return lessToCss;
});
```

**编译前**
```less
.grid {
    background: #fff;
    .row {
        background: #fff;
    }
}
```

**编译后**
```css
.grid___kW3k9 {
  background: #fff;
}
.grid___kW3k9 .row___-u05H {
  background: #fff;
}
:export {
  grid: grid___kW3k9;
  row: row___-u05H;
}
```
